<?php  //[STAMP] c34abe4dae191bc1f4bef8d3efa0beda
namespace SongbirdNestablePageBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use SongbirdNestablePageBundle\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
