<?php

namespace Songbird\NestablePageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{

    public function findPageMetaByLocale($slug, $locale) {

        $query = $this->createQueryBuilder('p')
            ->select('p', 'pm')
            ->Join('p.pageMetas','pm')
            ->where('p.isPublished = :isPublished')
            ->andWhere('pm.locale = :locale')
            ->andWhere('p.slug = :slug')
            ->setParameter('isPublished', '1')
            ->setParameter('locale', $locale)
            ->setParameter('slug', $slug)
            ->getQuery();

        return $query->getOneOrNullResult();

    }

    /**
     * get root node
     *
     * $publish = 0, displays all unpublished nodes
     * $publish = 1, displays all published nodes
     * $publish = 2, displays all nodes
     * @param  integer $published 
     * @return $query
     */
    public function findParent($published = 2) {

        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->Where('p.parent is null')
            ->orderBy('p.sequence', 'asc');

        if ($published < 2) {
            $query->andWhere('p.isPublished = :isPublished')
            ->setParameter('isPublished', $published);
        }

        return $query->getQuery()->getResult();

    }
}
