#!/bin/bash

usage()
{
cat << EOF

usage: $0 [options]

This script clears the cache, resets the db and install the fixtures 

OPTIONS:
   -f      Don't load fixtures
   -c      Don't clear cache (for all env)
EOF
exit 1
}

CLEAR_CACHE=1
LOAD_FIXTURES=1
while getopts "cf" o; do
    case "${o}" in
        c)
            CLEAR_CACHE=
            ;;
        f)
            LOAD_FIXTURES=
            ;;
        *)
            usage
            ;;
    esac
done

if [[ $CLEAR_CACHE ]]
then
	rm -rf app/cache/*
fi

app/console doctrine:database:drop --force
app/console doctrine:database:create
app/console doctrine:schema:create

if [[ $LOAD_FIXTURES ]]
then
    app/console doctrine:fixtures:load -n
fi
